// Auto-generated by scripts/build-popular-destinations.mjs — do not edit by hand.

export type PopularDestination = {
  kind: "city" | "country";
  countryCode: string;
  cityName: string;
  label: string;
  countryName: string;
  latitude: number;
  longitude: number;
};

export const POPULAR_DESTINATIONS: PopularDestination[] = [
  {
    "kind": "city",
    "countryCode": "FR",
    "cityName": "Paris",
    "label": "Paris",
    "countryName": "France",
    "latitude": 48.8566,
    "longitude": 2.3522
  },
  {
    "kind": "city",
    "countryCode": "GB",
    "cityName": "London",
    "label": "London",
    "countryName": "UK (United Kingdom)",
    "latitude": 51.5074,
    "longitude": -0.1278
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "New York",
    "label": "New York City, NY",
    "countryName": "United States (United States of America)",
    "latitude": 40.7602,
    "longitude": -73.9761
  },
  {
    "kind": "city",
    "countryCode": "IT",
    "cityName": "Rome",
    "label": "Rome",
    "countryName": "Italy",
    "latitude": 41.9028,
    "longitude": 12.4964
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Orlando",
    "label": "Orlando, FL",
    "countryName": "United States (United States of America)",
    "latitude": 28.5677,
    "longitude": -81.2887
  },
  {
    "kind": "city",
    "countryCode": "ES",
    "cityName": "Barcelona",
    "label": "Barcelona",
    "countryName": "Spain",
    "latitude": 41.3851,
    "longitude": 2.1734
  },
  {
    "kind": "city",
    "countryCode": "NL",
    "cityName": "Amsterdam",
    "label": "Amsterdam",
    "countryName": "The Netherlands (Netherlands)",
    "latitude": 52.3676,
    "longitude": 4.9041
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Los Angeles",
    "label": "Los Angeles, CA",
    "countryName": "United States (United States of America)",
    "latitude": 34.0689,
    "longitude": -118.2516
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Las Vegas",
    "label": "Las Vegas, NV",
    "countryName": "United States (United States of America)",
    "latitude": 36.1126,
    "longitude": -115.1767
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Washington",
    "label": "Washington, DC",
    "countryName": "United States (United States of America)",
    "latitude": 38.8894,
    "longitude": -77.0405
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Miami",
    "label": "Miami, FL",
    "countryName": "United States (United States of America)",
    "latitude": 25.6468,
    "longitude": -80.4124
  },
  {
    "kind": "city",
    "countryCode": "IT",
    "cityName": "Venice",
    "label": "Venice",
    "countryName": "Italy",
    "latitude": 45.4408,
    "longitude": 12.3155
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "San Francisco",
    "label": "San Francisco, CA",
    "countryName": "United States (United States of America)",
    "latitude": 37.8199,
    "longitude": -122.4783
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Chicago",
    "label": "Chicago, IL",
    "countryName": "United States (United States of America)",
    "latitude": 41.8939,
    "longitude": -87.6246
  },
  {
    "kind": "city",
    "countryCode": "IT",
    "cityName": "Florence",
    "label": "Florence",
    "countryName": "Italy",
    "latitude": 43.7696,
    "longitude": 11.2558
  },
  {
    "kind": "city",
    "countryCode": "ES",
    "cityName": "Madrid",
    "label": "Madrid",
    "countryName": "Spain",
    "latitude": 40.4168,
    "longitude": -3.7038
  },
  {
    "kind": "city",
    "countryCode": "DE",
    "cityName": "Berlin",
    "label": "Berlin",
    "countryName": "Germany",
    "latitude": 52.52,
    "longitude": 13.405
  },
  {
    "kind": "city",
    "countryCode": "IT",
    "cityName": "Milan",
    "label": "Milan",
    "countryName": "Italy",
    "latitude": 45.4642,
    "longitude": 9.19
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Boston",
    "label": "Boston, MA",
    "countryName": "United States (United States of America)",
    "latitude": 42.363,
    "longitude": -71.0561
  },
  {
    "kind": "city",
    "countryCode": "CZ",
    "cityName": "Prague",
    "label": "Prague",
    "countryName": "Czechia (Czech Republic)",
    "latitude": 50.0911,
    "longitude": 14.4016
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Atlanta",
    "label": "Atlanta, GA",
    "countryName": "United States (United States of America)",
    "latitude": 33.6367,
    "longitude": -84.4281
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "San Diego",
    "label": "San Diego, CA",
    "countryName": "United States (United States of America)",
    "latitude": 32.7336,
    "longitude": -117.19
  },
  {
    "kind": "city",
    "countryCode": "BE",
    "cityName": "Brussels",
    "label": "Brussels",
    "countryName": "Belgium",
    "latitude": 50.8429,
    "longitude": 4.3576
  },
  {
    "kind": "city",
    "countryCode": "AT",
    "cityName": "Vienna",
    "label": "Vienna",
    "countryName": "Austria",
    "latitude": 48.21,
    "longitude": 16.3573
  },
  {
    "kind": "city",
    "countryCode": "MX",
    "cityName": "Cancún",
    "label": "Cancún",
    "countryName": "Mexico",
    "latitude": 21.1322,
    "longitude": -86.7456
  },
  {
    "kind": "city",
    "countryCode": "DE",
    "cityName": "Munich",
    "label": "Munich",
    "countryName": "Germany",
    "latitude": 48.1351,
    "longitude": 11.582
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Dallas",
    "label": "Dallas, TX",
    "countryName": "United States (United States of America)",
    "latitude": 32.7591,
    "longitude": -96.783
  },
  {
    "kind": "city",
    "countryCode": "PT",
    "cityName": "Lisbon",
    "label": "Lisbon",
    "countryName": "Portugal",
    "latitude": 38.6916,
    "longitude": -9.216
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Denver",
    "label": "Denver, CO",
    "countryName": "United States (United States of America)",
    "latitude": 39.86,
    "longitude": -104.6738
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Philadelphia",
    "label": "Philadelphia, PA",
    "countryName": "United States (United States of America)",
    "latitude": 39.9489,
    "longitude": -75.15
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Nashville",
    "label": "Nashville, TN",
    "countryName": "United States (United States of America)",
    "latitude": 36.1604,
    "longitude": -86.7784
  },
  {
    "kind": "city",
    "countryCode": "IE",
    "cityName": "Dublin",
    "label": "Dublin",
    "countryName": "Ireland",
    "latitude": 53.3419,
    "longitude": -6.2869
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Seattle",
    "label": "Seattle, WA",
    "countryName": "United States (United States of America)",
    "latitude": 47.4479,
    "longitude": -122.3103
  },
  {
    "kind": "city",
    "countryCode": "HU",
    "cityName": "Budapest",
    "label": "Budapest",
    "countryName": "Hungary",
    "latitude": 47.5076,
    "longitude": 19.0459
  },
  {
    "kind": "city",
    "countryCode": "GB",
    "cityName": "Edinburgh",
    "label": "Edinburgh",
    "countryName": "UK (United Kingdom)",
    "latitude": 55.9533,
    "longitude": -3.1883
  },
  {
    "kind": "city",
    "countryCode": "GR",
    "cityName": "Athens",
    "label": "Athens",
    "countryName": "Greece",
    "latitude": 37.9838,
    "longitude": 23.7275
  },
  {
    "kind": "city",
    "countryCode": "VA",
    "cityName": "Vatican City",
    "label": "Vatican City",
    "countryName": "Vatican",
    "latitude": 41.9022,
    "longitude": 12.4539
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "New Orleans",
    "label": "New Orleans, LA",
    "countryName": "United States (United States of America)",
    "latitude": 29.9584,
    "longitude": -90.0644
  },
  {
    "kind": "city",
    "countryCode": "IT",
    "cityName": "Pisa",
    "label": "Pisa",
    "countryName": "Italy",
    "latitude": 43.7228,
    "longitude": 10.4017
  },
  {
    "kind": "city",
    "countryCode": "CA",
    "cityName": "Toronto",
    "label": "Toronto, ON",
    "countryName": "Canada",
    "latitude": 43.6511,
    "longitude": -79.3774
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Houston",
    "label": "Houston, TX",
    "countryName": "United States (United States of America)",
    "latitude": 29.6453,
    "longitude": -95.2768
  },
  {
    "kind": "city",
    "countryCode": "DE",
    "cityName": "Frankfurt",
    "label": "Frankfurt",
    "countryName": "Germany",
    "latitude": 50.1109,
    "longitude": 8.6821
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Phoenix",
    "label": "Phoenix, AZ",
    "countryName": "United States (United States of America)",
    "latitude": 33.4353,
    "longitude": -112.0059
  },
  {
    "kind": "city",
    "countryCode": "TH",
    "cityName": "Bangkok",
    "label": "Bangkok",
    "countryName": "Thailand",
    "latitude": 13.7261,
    "longitude": 100.5108
  },
  {
    "kind": "city",
    "countryCode": "TR",
    "cityName": "Istanbul",
    "label": "Istanbul",
    "countryName": "Turkey (Türkiye)",
    "latitude": 41.0176,
    "longitude": 28.9711
  },
  {
    "kind": "city",
    "countryCode": "AE",
    "cityName": "Dubai",
    "label": "Dubai",
    "countryName": "UAE (United Arab Emirates)",
    "latitude": 25.1972,
    "longitude": 55.2744
  },
  {
    "kind": "city",
    "countryCode": "FR",
    "cityName": "Nice",
    "label": "Nice",
    "countryName": "France",
    "latitude": 43.7102,
    "longitude": 7.262
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Tampa",
    "label": "Tampa, FL",
    "countryName": "United States (United States of America)",
    "latitude": 27.9755,
    "longitude": -82.5332
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Fort Lauderdale",
    "label": "Fort Lauderdale, FL",
    "countryName": "United States (United States of America)",
    "latitude": 26.0987,
    "longitude": -80.1373
  },
  {
    "kind": "city",
    "countryCode": "DK",
    "cityName": "Copenhagen",
    "label": "Copenhagen",
    "countryName": "Denmark",
    "latitude": 55.6737,
    "longitude": 12.5682
  },
  {
    "kind": "city",
    "countryCode": "CA",
    "cityName": "Vancouver",
    "label": "Vancouver, BC",
    "countryName": "Canada",
    "latitude": 49.3043,
    "longitude": -123.1443
  },
  {
    "kind": "city",
    "countryCode": "JP",
    "cityName": "Tokyo",
    "label": "Tokyo",
    "countryName": "Japan",
    "latitude": 35.7156,
    "longitude": 139.773
  },
  {
    "kind": "city",
    "countryCode": "CH",
    "cityName": "Zurich",
    "label": "Zürich",
    "countryName": "Switzerland",
    "latitude": 47.4581,
    "longitude": 8.5481
  },
  {
    "kind": "city",
    "countryCode": "IT",
    "cityName": "Naples",
    "label": "Naples",
    "countryName": "Italy",
    "latitude": 40.8518,
    "longitude": 14.2681
  },
  {
    "kind": "city",
    "countryCode": "CA",
    "cityName": "Montréal",
    "label": "Montreal, QC",
    "countryName": "Canada",
    "latitude": 45.5045,
    "longitude": -73.5561
  },
  {
    "kind": "city",
    "countryCode": "AU",
    "cityName": "Sydney",
    "label": "Sydney",
    "countryName": "Australia",
    "latitude": -33.8568,
    "longitude": 151.2153
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "San Antonio",
    "label": "San Antonio, TX",
    "countryName": "United States (United States of America)",
    "latitude": 29.426,
    "longitude": -98.4861
  },
  {
    "kind": "city",
    "countryCode": "CA",
    "cityName": "Niagara Falls",
    "label": "Niagara Falls, ON",
    "countryName": "Canada",
    "latitude": 43.0848,
    "longitude": -79.0784
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Baltimore",
    "label": "Baltimore, MD",
    "countryName": "United States (United States of America)",
    "latitude": 39.1754,
    "longitude": -76.6683
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Charlotte",
    "label": "Charlotte, NC",
    "countryName": "United States (United States of America)",
    "latitude": 35.214,
    "longitude": -80.9431
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Austin",
    "label": "Austin, TX",
    "countryName": "United States (United States of America)",
    "latitude": 30.2672,
    "longitude": -97.7431
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "St. Louis",
    "label": "St. Louis, MO",
    "countryName": "United States (United States of America)",
    "latitude": 38.627,
    "longitude": -90.1994
  },
  {
    "kind": "city",
    "countryCode": "BS",
    "cityName": "Nassau",
    "label": "Nassau",
    "countryName": "Bahamas",
    "latitude": 25.039,
    "longitude": -77.4662
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Key West",
    "label": "Key West, FL",
    "countryName": "United States (United States of America)",
    "latitude": 24.5512,
    "longitude": -81.8006
  },
  {
    "kind": "city",
    "countryCode": "BE",
    "cityName": "Brugge",
    "label": "Bruges",
    "countryName": "Belgium",
    "latitude": 51.2093,
    "longitude": 3.2247
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Salt Lake City",
    "label": "Salt Lake City, UT",
    "countryName": "United States (United States of America)",
    "latitude": 40.7889,
    "longitude": -111.9799
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Honolulu",
    "label": "Honolulu, HI",
    "countryName": "United States (United States of America)",
    "latitude": 21.2791,
    "longitude": -157.8258
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Indianapolis",
    "label": "Indianapolis, IN",
    "countryName": "United States (United States of America)",
    "latitude": 39.7173,
    "longitude": -86.2944
  },
  {
    "kind": "city",
    "countryCode": "GB",
    "cityName": "Manchester",
    "label": "Manchester",
    "countryName": "UK (United Kingdom)",
    "latitude": 53.4808,
    "longitude": -2.2426
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Charleston",
    "label": "Charleston, SC",
    "countryName": "United States (United States of America)",
    "latitude": 32.7754,
    "longitude": -79.9273
  },
  {
    "kind": "city",
    "countryCode": "PT",
    "cityName": "Porto",
    "label": "Porto",
    "countryName": "Portugal",
    "latitude": 41.1579,
    "longitude": -8.6291
  },
  {
    "kind": "city",
    "countryCode": "MX",
    "cityName": "Mexico City",
    "label": "Mexico City",
    "countryName": "Mexico",
    "latitude": 19.4326,
    "longitude": -99.1392
  },
  {
    "kind": "city",
    "countryCode": "ES",
    "cityName": "Seville",
    "label": "Seville",
    "countryName": "Spain",
    "latitude": 37.3891,
    "longitude": -5.9845
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Portland",
    "label": "Portland, OR",
    "countryName": "United States (United States of America)",
    "latitude": 45.5187,
    "longitude": -122.6781
  },
  {
    "kind": "city",
    "countryCode": "ES",
    "cityName": "Malaga",
    "label": "Málaga",
    "countryName": "Spain",
    "latitude": 36.7213,
    "longitude": -4.4214
  },
  {
    "kind": "city",
    "countryCode": "SE",
    "cityName": "Stockholm",
    "label": "Stockholm",
    "countryName": "Sweden",
    "latitude": 59.3257,
    "longitude": 18.0719
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Savannah",
    "label": "Savannah, GA",
    "countryName": "United States (United States of America)",
    "latitude": 32.0809,
    "longitude": -81.0912
  },
  {
    "kind": "city",
    "countryCode": "CH",
    "cityName": "Geneva",
    "label": "Geneva",
    "countryName": "Switzerland",
    "latitude": 46.2044,
    "longitude": 6.1432
  },
  {
    "kind": "city",
    "countryCode": "DE",
    "cityName": "Hamburg",
    "label": "Hamburg",
    "countryName": "Germany",
    "latitude": 53.5511,
    "longitude": 9.9937
  },
  {
    "kind": "city",
    "countryCode": "DE",
    "cityName": "Cologne",
    "label": "Cologne",
    "countryName": "Germany",
    "latitude": 50.9375,
    "longitude": 6.9603
  },
  {
    "kind": "city",
    "countryCode": "US",
    "cityName": "Minneapolis",
    "label": "Minneapolis, MN",
    "countryName": "United States (United States of America)",
    "latitude": 44.8801,
    "longitude": -93.2217
  },
  {
    "kind": "city",
    "countryCode": "AT",
    "cityName": "Salzburg",
    "label": "Salzburg",
    "countryName": "Austria",
    "latitude": 47.8095,
    "longitude": 13.055
  },
  {
    "kind": "city",
    "countryCode": "BR",
    "cityName": "Rio de Janeiro",
    "label": "Rio de Janeiro",
    "countryName": "Brazil",
    "latitude": -22.9519,
    "longitude": -43.2105
  },
  {
    "kind": "city",
    "countryCode": "PL",
    "cityName": "Krakow",
    "label": "Kraków",
    "countryName": "Poland",
    "latitude": 50.0668,
    "longitude": 19.945
  },
  {
    "kind": "city",
    "countryCode": "FR",
    "cityName": "Marseille",
    "label": "Marseille",
    "countryName": "France",
    "latitude": 43.2965,
    "longitude": 5.3698
  },
  {
    "kind": "city",
    "countryCode": "DO",
    "cityName": "Punta Cana",
    "label": "Punta Cana",
    "countryName": "Dominican Republic",
    "latitude": 18.5671,
    "longitude": -68.3646
  },
  {
    "kind": "city",
    "countryCode": "ES",
    "cityName": "Valencia",
    "label": "Valencia",
    "countryName": "Spain",
    "latitude": 39.4699,
    "longitude": -0.3763
  },
  {
    "kind": "city",
    "countryCode": "SG",
    "cityName": "Singapore",
    "label": "Singapore",
    "countryName": "Singapore",
    "latitude": 1.3521,
    "longitude": 103.8198
  },
  {
    "kind": "city",
    "countryCode": "AR",
    "cityName": "Buenos Aires",
    "label": "Buenos Aires",
    "countryName": "Argentina",
    "latitude": -34.6012,
    "longitude": -58.3833
  },
  {
    "kind": "city",
    "countryCode": "IT",
    "cityName": "Verona",
    "label": "Verona",
    "countryName": "Italy",
    "latitude": 45.4384,
    "longitude": 10.9916
  },
  {
    "kind": "city",
    "countryCode": "HR",
    "cityName": "Dubrovnik",
    "label": "Dubrovnik",
    "countryName": "Croatia",
    "latitude": 42.6467,
    "longitude": 18.0991
  },
  {
    "kind": "city",
    "countryCode": "GB",
    "cityName": "Glasgow City",
    "label": "Glasgow",
    "countryName": "UK (United Kingdom)",
    "latitude": 55.8627,
    "longitude": -4.2311
  },
  {
    "kind": "city",
    "countryCode": "NO",
    "cityName": "Oslo",
    "label": "Oslo",
    "countryName": "Norway",
    "latitude": 59.9416,
    "longitude": 10.771
  },
  {
    "kind": "city",
    "countryCode": "GB",
    "cityName": "Liverpool",
    "label": "Liverpool",
    "countryName": "UK (United Kingdom)",
    "latitude": 53.4084,
    "longitude": -2.9916
  },
  {
    "kind": "city",
    "countryCode": "BR",
    "cityName": "São Paulo",
    "label": "São Paulo",
    "countryName": "Brazil",
    "latitude": -23.5505,
    "longitude": -46.6333
  }
];
