// Auto-generated by scripts/build-popular-parks.mjs — do not edit by hand.

import type { ParkType } from "@/lib/data/tourist-park-search";

export type PopularPark = {
  parkType: ParkType;
  countryCode: string;
  parkName: string;
  label: string;
  countryName: string;
};

export const POPULAR_PARKS: PopularPark[] = [
  {
    "parkType": "national_park",
    "countryCode": "US",
    "parkName": "Yellowstone",
    "label": "Yellowstone",
    "countryName": "United States (United States of America)"
  },
  {
    "parkType": "national_park",
    "countryCode": "US",
    "parkName": "Grand Canyon",
    "label": "Grand Canyon",
    "countryName": "United States (United States of America)"
  },
  {
    "parkType": "national_park",
    "countryCode": "US",
    "parkName": "Yosemite",
    "label": "Yosemite",
    "countryName": "United States (United States of America)"
  },
  {
    "parkType": "national_park",
    "countryCode": "CA",
    "parkName": "Banff",
    "label": "Banff",
    "countryName": "Canada"
  },
  {
    "parkType": "national_park",
    "countryCode": "ZA",
    "parkName": "Kruger",
    "label": "Kruger",
    "countryName": "South Africa"
  },
  {
    "parkType": "national_park",
    "countryCode": "TZ",
    "parkName": "Serengeti National Park",
    "label": "Serengeti",
    "countryName": "Tanzania (United Republic of Tanzania)"
  },
  {
    "parkType": "national_park",
    "countryCode": "CH",
    "parkName": "Swiss",
    "label": "Swiss National Park",
    "countryName": "Switzerland"
  },
  {
    "parkType": "national_park",
    "countryCode": "DE",
    "parkName": "Black Forest",
    "label": "Black Forest",
    "countryName": "Germany"
  },
  {
    "parkType": "national_park",
    "countryCode": "DE",
    "parkName": "Berchtesgaden",
    "label": "Berchtesgaden",
    "countryName": "Germany"
  },
  {
    "parkType": "national_park",
    "countryCode": "FR",
    "parkName": "Pyrénées",
    "label": "Pyrenees",
    "countryName": "France"
  },
  {
    "parkType": "national_park",
    "countryCode": "FR",
    "parkName": "Vanoise",
    "label": "Vanoise",
    "countryName": "France"
  },
  {
    "parkType": "national_park",
    "countryCode": "ES",
    "parkName": "Teide",
    "label": "Teide",
    "countryName": "Spain"
  },
  {
    "parkType": "national_park",
    "countryCode": "HR",
    "parkName": "Plitvice Lakes",
    "label": "Plitvice Lakes",
    "countryName": "Croatia"
  },
  {
    "parkType": "national_park",
    "countryCode": "GB",
    "parkName": "Lake District",
    "label": "Lake District",
    "countryName": "UK (United Kingdom)"
  },
  {
    "parkType": "national_park",
    "countryCode": "NO",
    "parkName": "Jotunheimen",
    "label": "Jotunheimen",
    "countryName": "Norway"
  },
  {
    "parkType": "national_park",
    "countryCode": "TR",
    "parkName": "Göreme",
    "label": "Göreme",
    "countryName": "Turkey (Türkiye)"
  },
  {
    "parkType": "national_park",
    "countryCode": "TR",
    "parkName": "Uludağ",
    "label": "Uludağ",
    "countryName": "Turkey (Türkiye)"
  },
  {
    "parkType": "national_park",
    "countryCode": "TH",
    "parkName": "James Bond Island (Ko Tapu)",
    "label": "James Bond Island",
    "countryName": "Thailand"
  },
  {
    "parkType": "national_park",
    "countryCode": "TH",
    "parkName": "Phi Phi Islands",
    "label": "Phi Phi Islands",
    "countryName": "Thailand"
  },
  {
    "parkType": "theme_park",
    "countryCode": "US",
    "parkName": "Disneyland",
    "label": "Disneyland",
    "countryName": "United States (United States of America)"
  },
  {
    "parkType": "theme_park",
    "countryCode": "US",
    "parkName": "Walt Disney World Resort",
    "label": "Walt Disney World",
    "countryName": "United States (United States of America)"
  },
  {
    "parkType": "theme_park",
    "countryCode": "US",
    "parkName": "Universal Studios Florida",
    "label": "Universal Studios",
    "countryName": "United States (United States of America)"
  },
  {
    "parkType": "theme_park",
    "countryCode": "NL",
    "parkName": "Efteling",
    "label": "Efteling",
    "countryName": "The Netherlands (Netherlands)"
  },
  {
    "parkType": "theme_park",
    "countryCode": "DE",
    "parkName": "Europa-Park",
    "label": "Europa-Park",
    "countryName": "Germany"
  },
  {
    "parkType": "theme_park",
    "countryCode": "DE",
    "parkName": "Phantasialand",
    "label": "Phantasialand",
    "countryName": "Germany"
  },
  {
    "parkType": "theme_park",
    "countryCode": "FR",
    "parkName": "Disneyland Paris",
    "label": "Disneyland Paris",
    "countryName": "France"
  },
  {
    "parkType": "theme_park",
    "countryCode": "FR",
    "parkName": "Parc Astérix",
    "label": "Parc Astérix",
    "countryName": "France"
  },
  {
    "parkType": "theme_park",
    "countryCode": "ES",
    "parkName": "PortAventura Park",
    "label": "PortAventura",
    "countryName": "Spain"
  },
  {
    "parkType": "theme_park",
    "countryCode": "IT",
    "parkName": "Gardaland",
    "label": "Gardaland",
    "countryName": "Italy"
  },
  {
    "parkType": "theme_park",
    "countryCode": "GB",
    "parkName": "Alton Towers",
    "label": "Alton Towers",
    "countryName": "UK (United Kingdom)"
  },
  {
    "parkType": "theme_park",
    "countryCode": "SE",
    "parkName": "Liseberg",
    "label": "Liseberg",
    "countryName": "Sweden"
  },
  {
    "parkType": "theme_park",
    "countryCode": "DK",
    "parkName": "Legoland Billund",
    "label": "Legoland",
    "countryName": "Denmark"
  },
  {
    "parkType": "theme_park",
    "countryCode": "BE",
    "parkName": "Plopsaland Belgium",
    "label": "Plopsaland",
    "countryName": "Belgium"
  },
  {
    "parkType": "theme_park",
    "countryCode": "JP",
    "parkName": "Tokyo Disneyland",
    "label": "Tokyo Disneyland",
    "countryName": "Japan"
  },
  {
    "parkType": "botanical_garden",
    "countryCode": "TH",
    "parkName": "Nong Nooch",
    "label": "Nong Nooch",
    "countryName": "Thailand"
  },
  {
    "parkType": "national_park",
    "countryCode": "US",
    "parkName": "Niagara Falls",
    "label": "Niagara Falls",
    "countryName": "United States (United States of America)"
  },
  {
    "parkType": "national_park",
    "countryCode": "FR",
    "parkName": "French Alps",
    "label": "French Alps",
    "countryName": "France"
  },
  {
    "parkType": "national_park",
    "countryCode": "IT",
    "parkName": "Lake Garda",
    "label": "Lake Garda",
    "countryName": "Italy"
  },
  {
    "parkType": "national_park",
    "countryCode": "GB",
    "parkName": "Stonehenge",
    "label": "Stonehenge",
    "countryName": "UK (United Kingdom)"
  },
  {
    "parkType": "national_park",
    "countryCode": "EG",
    "parkName": "Dead Sea",
    "label": "Dead Sea",
    "countryName": "Egypt"
  },
  {
    "parkType": "national_park",
    "countryCode": "IT",
    "parkName": "Vesuvius",
    "label": "Vesuvius",
    "countryName": "Italy"
  },
  {
    "parkType": "national_park",
    "countryCode": "GB",
    "parkName": "Scottish Highlands",
    "label": "Scottish Highlands",
    "countryName": "UK (United Kingdom)"
  }
];
